"""How many distinct terms are in the sequence generated by ab for
2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
"""

distinct_pow = set()
for base in range(2, 101):
    for exponent in range(2, 101):
        result = pow(base, exponent)
        distinct_pow.add(result)

print(len(distinct_pow))
