# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
def problem_2(n):
    fibonacci = [1, 2]
    last = 2

    while last <= n:
        last = (fibonacci[-2] + last)
        if last <= n:
            fibonacci.append(last)
            last = fibonacci[-1]
        else:
            break

    fibonacci_even = []

    for even in fibonacci:
        if even % 2 == 0:
            fibonacci_even.append(even)

    print(sum(fibonacci_even))


problem_2(4_000_000)


